version: "3.8"
services:
  cassandra:
    image: omvk97/cassandra # this image will initialize the database
    container_name: cassandra
    environment:
      CASSANDRA_SEEDS: cassandra
      CASSANDRA_CLUSTER_NAME: DevCluster
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_DC: Denmark
    ports:
      - 9043:9042
      - 7001:7000
    volumes:
      - "./cassandra/init.cql:/docker-entrypoint-initdb.d/init.cql"

  packageservice:
    image: omvk97/packageservice
    container_name: packageservice
    env_file:
      - .env
    depends_on:
      - cassandra
